openapi: 3.0.3
info:
  description: >
    API til at hente og gruppere data fra Energinets Production and Consumption - 
    Settlement datasæt.
  title: Energi Data API
  version: "1.0.0"
servers:
  - url: http://api:8282
    description: Local server

paths:
  /production:
    get:
      summary: Hen rå produktions data
      operationId: getProduction
      tags:
        - Raw
      parameters:
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
        - $ref: '#/components/parameters/priceArea'
        - $ref: '#/components/parameters/productionType'
      responses:
        200:
          description: Produktionsdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Productions'
        "400":
          description: Bad request - invalid date format or parameters
        "404":
          description: No data found for the specified criteria
      x-accepts:
        - application/json

  /production/total:
    get:
      summary: Hent produktionsdata
      operationId: getProductionTotal
      tags:
        - Derived
      parameters:
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
      responses:
        '200':
          description: Produktionsdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionResponse'

  /consumption:
    get:
      summary: Hent rå forbrugsdata
      operationId: getConsumption
      tags:
        - Raw
      parameters:
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
        - $ref: '#/components/parameters/priceArea'
      responses:
        200:
          description: Rå forbrugsdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumptions'
        "400":
          description: Bad request - invalid date format or parameters
        "404":
          description: No data found for the specified criteria
      x-accepts:
        - application/json

  /consumption/total:
    get:
      summary: Hent forbrugsdata
      operationId: getConsumptionTotal
      tags:
        - Derived
      parameters:
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
        - $ref: '#/components/parameters/priceArea'
      responses:
        '200':
          description: Forbrugsdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsumptionTotal'
        "400":
          description: Bad request - invalid date format or parameters
        "404":
          description: No data found for the specified criteria

  /exchange:
    get:
      summary: Hent rå udvekslingsdata med andre lande
      operationId: getExchange
      tags:
        - Raw
      parameters:
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
        - $ref: '#/components/parameters/priceArea'
      responses:
        200:
          description: Rå udvekslingsdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeEntries'
        "400":
          description: Bad request - invalid date format or parameters
        "404":
          description: No data found for the specified criteria
      x-accepts:
        - application/json
  /exchange/country:
    get:
      summary: Hent udvekslingsdata med andre lande
      operationId: getExchangeCountry
      tags:
        - Derived
      parameters:
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
      responses:
        200:
          description: Rå forbrugsdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exchange'
        "400":
          description: Bad request - invalid date format or parameters
        "404":
          description: No data found for the specified criteria
        "500":
          description: Internal server error
        x-accepts:
          - application/json

  /model/upload:
    post:
      summary: Upload a new RL model (policy.pt) as base64 or file
      operationId: uploadModel
      tags:
        - Model Management
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                modelName:
                  type: string
                  description: Name of the model
                description:
                  type: string
                  description: Optional description
                file:
                  type: string
                  format: binary
                  description: The policy.pt file (max 1MB, .pt only)
                base64:
                  type: string
                  description: Base64-encoded model file (alternative to file)
            encoding:
              file:
                contentType: application/octet-stream
          application/json:
            schema:
              type: object
              properties:
                modelName:
                  type: string
                description:
                  type: string
                base64:
                  type: string
      responses:
        "201":
          description: Model uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        "400":
          description: Invalid input or file too large/wrong type
        "401":
          description: Unauthorized

  /model/latest:
    get:
      summary: Fetch the latest RL model (as base64 or file)
      operationId: getLatestModel
      tags:
        - Model Management
      parameters:
        - $ref: '#/components/parameters/asFile'
      responses:
        "200":
          description: Latest model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          description: No model found
        "401":
          description: Unauthorized

  /model/list:
    get:
      summary: List all model versions/metadata
      operationId: listModels
      tags:
        - Model Management
      responses:
        "200":
          description: List of models
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelMetadata'
        "401":
          description: Unauthorized
  /model/{id}:
    patch:
      summary: Update model metadata or description
      operationId: updateModelMetadata
      tags:
        - Model Management
      parameters:
        - $ref: '#/components/parameters/modelId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                modelName:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: Metadata updated
        "404":
          description: Model not found
        "401":
          description: Unauthorized

  /load/specific/{id}:
    get:
      summary: load a specific caching model
      operationId: loadCachingModel
      tags:
        - Model Management
      parameters:
        - $ref: '#/components/parameters/modelId'
        - $ref: '#/components/parameters/modelType'
      responses:
        "200":
          description: Model loaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelMetadata'
        "404":
          description: Model not found
        "401":
          description: Unauthorized
  /load/strategy:
    get:
      summary: Get the current strategy
      operationId: getModelStrategy
      tags:
        - Model Management
      responses:
        "200":
          description: Model strategy
          content:
            application/json:
              schema:
                type: object
                properties:
                  strategy:
                    type: string
        "404":
          description: Model not found
        "401":
          description: Unauthorized

components:
  parameters:
    modelId:
      name: id
      in: path
      required: true
      schema:
        type: integer
        example: 123
      description: The ID of the model to fetch or update

    modelType:
      name: modelType
      in: query
      required: false
      schema:
        type: string
        example: DQN
      description: The type of the model (e.g., DQN, A2C, PPO, LRU, LFU, TTL, NONE)

    asFile:
      name: asFile
      in: query
      required: false
      schema:
        type: boolean
        example: true
      description: If true, returns the model as a file download

    from:
      name: from
      description: ISO 8601 format (e.g., 2024-01-01T00:00)
      in: query
      required: true
      schema:
        type: string
        format: date-time
        example: 2024-01-01T00:00

    to:
      name: to
      description: ISO 8601 format (e.g., 2024-02-01T00:00)
      in: query
      required: true
      schema:
        type: string
        format: date-time
        example: 2024-01-01T00:00

    priceArea:
      name: priceArea
      in: query
      description: >
        Prisområde (DK1 eller DK2). 
        Brug "--" for at hente data for alle prisområder.
      required: false
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/PriceAreaEnum'

    productionType:
      name: type
      in: query
      description: Specify the type of the source of the energy
      required: false
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/ProductionTypeEnum'

    exchangeCountry:
      name: country
      in: query
      description: Which country the exchange happens to
      required: false
      explode: true
      schema:
        $ref: '#/components/schemas/ExchangeCountryEnum'

  schemas:
    PriceAreaEnum:
      type: string
      enum:
        - DK1
        - DK2

    ProductionTypeEnum:
      type: string
      enum:
        - WIND
        - SOLAR
        - HYDRO
        - COMMERCIAL_POWER
        - CENTRAL_POWER

    ExchangeCountryEnum:
      type: string
      default: germany
      enum:
        - germany
        - greatbritain
        - netherlands
        - norway
        - sweden


    ProductionMisc:
      type: object
      properties:
        CentralPower_MWh:
          type: number
        LocalPower_MWh:
          type: number
        CommercialPower_MWh:
          type: number
        CommercialPowerSelfConsumption_MWh:
          type: number
        HydroPower_MWh:
          type: number

    ProductionWind:
      type: object
      properties:
        WindTotal_MWh:
          type: number
        OffshoreWindTotal_MWh:
          type: number
        OffshoreWindLt100MW_MWh:
          type: number
        OffshoreWindGe100MW_MWh:
          type: number
        OnshoreWindTotal_MWh:
          type: number
        OnshoreWindGe50kW_MWh:
          type: number

    ProductionSolar:
      type: object
      properties:
        SolarTotal_MWh:
          type: number
        SolarTotalNoSelfConsumption_MWh:
          type: number
        SolarPowerSelfConsumption_MWh:
          type: number
        SolarPowerLt10kW_MWh:
          type: number
        SolarPowerGe10Lt40kW_MWh:
          type: number
        SolarPowerGe40kW_MWh:
          type: number

    UsageConsumption:
      type: object
      properties:
        ConsumptionTotal_MWh:
          type: number
        ConsumptionPrivate_MWh:
          type: number
        ConsumptionPublicTotal_MWh:
          type: number
        ConsumptionCommertialTotal_MWh:
          type: number
    UsageLoss:
      type: object
      properties:
        GridLossTransmission_MWh:
          type: number
        GridLossDistribution_MWh:
          type: number
        GridLossInterconnectors_MWh:
          type: number
    UsageMisc:
      type: object
      properties:
        PowerToHeatMWh:
          type: number
    Exchange:
      type: object
      properties:
        ExchangeNO_MWh:
          type: number
        ExchangeSE_MWh:
          type: number
        ExchangeDE_MWh:
          type: number
        ExchangeNL_MWh:
          type: number
        ExchangeGB_MWh:
          type: number
        ExchangeGBB_MWh:
          type: number
      example:
        ExchangeGB_MWh: 5.637376656633329
        ExchangeNO_MWh: 0.8008281904610115
        ExchangeSE_MWh: 6.027456183070403
        ExchangeDE_MWh: 1.4658129805029452
        ExchangeGBB_MWh: 2.3021358869347655
        ExchangeNL_MWh: 5.962133916683182

    ExchangeData:
      type: object
      properties:
        HourUTC:
          type: string
          format: date-time
        Country:
          type: string
        Export_MWh:
          type: number
        Import_MWh:
          type: number
        NetExchange_MWh:
          type: number
      example:
        HourUTC: "2000-01-23T04:56:07.000+00:00"
        Country: "norway"
        Export_MWh: 120.5
        Import_MWh: 75.2
        NetExchange_MWh: 45.3

    ProductionResponse:
      allOf:
        - $ref: '#/components/schemas/ProductionWind'
        - $ref: '#/components/schemas/ProductionSolar'
        - $ref: '#/components/schemas/ProductionMisc'
      example:
        CommercialPowerSelfConsumption_MWh: 6.84685269835264
        OnshoreWindTotal_MWh: 5.637376656633329
        OffshoreWindTotal_MWh: 6.027456183070403
        CommercialPower_MWh: 1.4894159098541704
        OffshoreWindLt100MW_MWh: 1.4658129805029452
        OffshoreWindGe100MW_MWh: 5.962133916683182
        SolarTotalNoSelfConsumption_MWh: 9.301444243932576
        LocalPower_MWh: 1.0246457001441578
        HydroPower_MWh: 7.457744773683766
        OnshoreWindGe50kW_MWh: 2.3021358869347655
        SolarPowerSelfConsumption_MWh: 3.616076749251911
        CentralPower_MWh: 1.2315135367772556
        SolarPowerGe40kW_MWh: 7.386281948385884
        SolarTotal_MWh: 7.061401241503109
        SolarPowerGe10Lt40kW_MWh: 4.145608029883936
        WindTotal_MWh: 0.8008281904610115
        SolarPowerLt10kW_MWh: 2.027123023002322


    ConsumptionTotal:
      type: object
      properties:
        totalConsumptionMWh:
          type: number
        fromDate:
          type: string
          format: date-time
        toDate:
          type: string
          format: date-time
        branche:
          $ref: '#/components/schemas/BrancheData'
        DK1:
          $ref: '#/components/schemas/RegionalConsumption'
        DK2:
          $ref: '#/components/schemas/RegionalConsumption'


    ConsumptionResponse:
      allOf:
        - type: object
          properties:
            Timestamp:
              type: string
              format: timestamp
            PriceArea:
              type: string
        - $ref: '#/components/schemas/UsageConsumption'
        - $ref: '#/components/schemas/UsageLoss'
        - $ref: '#/components/schemas/UsageMisc'
      example:
        Timestamp: "2000-01-23T04:56:07.000+00:00"
        PriceArea: "DK1"
        PowerToHeatMWh: 9.301444243932576
        ConsumptionTotal_MWh: 0.8008281904610115
        GridLossTransmission_MWh: 5.637376656633329
        ConsumptionCommertialTotal_MWh: 5.962133916683182
        ConsumptionPublicTotal_MWh: 1.4658129805029452
        ConsumptionPrivate_MWh: 6.027456183070403
        GridLossInterconnectors_MWh: 7.061401241503109
        GridLossDistribution_MWh: 2.3021358869347655



    BrancheData:
      type: object
      properties:
        privatMWh:
          type: number
        offentligMWh:
          type: number
        erhvervMWh:
          type: number

    RegionalConsumption:
      type: object
      properties:
        totalConsumptionMWh:
          type: number
        branche:
          $ref: '#/components/schemas/BrancheData'
        municipalities:
          type: array
          items:
            $ref: '#/components/schemas/MunicipalityData'

    MunicipalityData:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        totalConsumptionMWh:
          type: number
        branche:
          $ref: '#/components/schemas/BrancheData'
    Model:
      type: object
      properties:
        id:
          type: integer
        modelName:
          type: string
        createdAt:
          type: string
          format: date-time
        description:
          type: string
        modelBase64:
          type: string
          description: Base64-encoded model file
        modelType:
          type: string
          description: Type of the model (e.g., DQN, A2C, PPO, LRU, LFU, TTL, NONE)

    ModelMetadata:
      type: object
      properties:
        id:
          type: integer
        modelName:
          type: string
        createdAt:
          type: string
          format: date-time
        description:
          type: string
        modelType:
          type: string
          description: Type of the model (e.g., DQN, A2C, PPO, LRU, LFU, TTL, NONE)


    Consumptions:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Consumption'

    Consumption:
      type: object
      properties:
        hourUTC:
          type: string
          format: date-time
        municipality_id:
          type: integer
        branche_id:
          type: integer
        consumption:
          type: number

    Productions:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Production'

    Production:
      type: object
      properties:
        hourUTC:
          type: string
          format: date-time
        priceArea:
          type: string
        central_power:
          type: number
        local_power:
          type: number
        commercial_power:
          type: number
        commercial_power_self_consumption:
          type: number
        offshore_wind_lt_100mw:
          type: number
        offshore_wind_ge_100mw:
          type: number
        onshore_wind_lt_50kw:
          type: number
        onshore_wind_ge_50kw:
          type: number
        hydro_power:
          type: number
        solar_power_lt_10kw:
          type: number
        solar_power_ge_10kw_lt_40kw:
          type: number
        solar_power_ge_40kw:
          type: number
        solar_power_self_consumption:
          type: number
        unknown_production:
          type: number

    ExchangeEntries:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ExchangeEntry'


    ExchangeEntry:
      type: object
      properties:
        hourUTC:
          type: string
          format: date-time
        priceArea:
          type: string
        norway:
          type: number
        sweden:
          type: number
        germany:
          type: number
        netherlands:
          type: number
        greatBritain:
          type: number
        greatBelt:
          type: number