services:
  ers-ml-trainer:
    build:
      context: ..
      dockerfile: Dockerfile
      target: gpu  # Default to CPU if TARGET is not set
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./cache_eval_results:/app/cache_eval_results
    environment:
      - DB_URL=mysql+mysqlconnector://cacheuser:cachepass@mariadb:3306/cache_db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}
              capabilities: [gpu]

  ers-mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=cache_db
      - MYSQL_USER=cacheuser
      - MYSQL_PASSWORD=cachepass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: