services:
  ers-ml-trainer:
    image: ers-ml-trainer:${TARGET:-cpu}
    build:
      context: ..
      dockerfile: docker/Dockerfile.${TARGET:-cpu}
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./cache_eval_results:/app/cache_eval_results
    environment:
      - DB_URL=mysql+mysqlconnector://cacheuser:cachepass@ers-mariadb:3306/cache_db
      - USE_GPU=${TARGET:-cpu}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}
              capabilities: [gpu]
              # This will only be used when GPU_COUNT > 0

  ers-mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=cache_db
      - MYSQL_USER=cacheuser
      - MYSQL_PASSWORD=cachepass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:

networks:
  default:
    name: ers-network