name: Docker Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-cpu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build CPU Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        target: cpu
        tags: ers-ml-trainer:cpu-test
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run linting for CPU
      run: |
        docker run --rm ers-ml-trainer:cpu-test flake8 .

    - name: Run tests for CPU
      run: |
        docker run --rm ers-ml-trainer:cpu-test pytest

    - name: Run application health check for CPU
      run: |
        docker run -d --name app-test-cpu -p 8000:8000 ers-ml-trainer:cpu-test
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        docker stop app-test-cpu

  test-gpu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build GPU Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        target: gpu
        tags: ers-ml-trainer:gpu-test
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run linting for GPU
      run: |
        docker run --rm ers-ml-trainer:gpu-test flake8 .

    - name: Run tests for GPU
      run: |
        docker run --rm ers-ml-trainer:gpu-test pytest

    - name: Run application health check for GPU
      run: |
        docker run -d --name app-test-gpu --gpus all -p 8000:8000 ers-ml-trainer:gpu-test
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        docker stop app-test-gpu