name: Python Packaging Workflow

on:
  push:
    branches:
      - main

jobs:
  package:
    if: contains(github.event.head_commit.message, '@package')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push CPU Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.cpu
          tags: |
            ghcr.io/${{ github.repository_owner }}/ers-ml-trainer:cpu-latest
            ghcr.io/${{ github.repository_owner }}/ers-ml-trainer:cpu-${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Build and Push GPU Docker Image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./docker/Dockerfile.gpu
#          tags: |
#            ghcr.io/${{ github.repository_owner }}/ers-ml-trainer:gpu-latest
#            ghcr.io/${{ github.repository_owner }}/ers-ml-trainer:gpu-${{ github.sha }}
#          push: true
#          cache-from: type=gha
#          cache-to: type=gha,mode=max